package cooking.view.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class AddCategoryController {
	@FXML
	private Button btn_addCategory;
	@FXML
	private Button btn_resetCat;

	// Event Listener on Button[#btn_resetCat].onAction
	@FXML
	public void resetCatButtonAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
