package cooking.view.design;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.util.List;

import cooking.model.concrete.Category;
import cooking.model.concrete.ObjectUtilities;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.control.MenuItem;

import javafx.scene.control.Label;

import javafx.scene.layout.BorderPane;

import javafx.scene.control.Menu;

public class TemplateController {
	@FXML
	private BorderPane bp_mainWindow;
	@FXML
	private MenuItem mi_close;
	@FXML
	private MenuItem mi_searchByRecipe;
	@FXML
	private MenuItem mi_searchByFoodComponent;
	@FXML
	private Menu menu_Category;
	@FXML
	private MenuItem menuItem_addCategory;
	@FXML
	private Label lbl_username;
	@FXML
	private TextField txt_searchByRecipe;
	@FXML
	private Button btn_SearchByRecipe;
	@FXML
	private Button btn_SearchByComponent;
	@FXML
	private TextField txt_searchByComponent;

	// Event Listener on MenuItem[#mi_close].onAction
	@FXML
	public void close(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Menu[#menu_Category].onAction
	@FXML
	public void getCategory(ActionEvent event) {
		// TODO Autogenerated
		List<Category> lc = ObjectUtilities.loadCategoryData();
		for(Category c: lc) {
			menu_Category.getItems().add(new MenuItem(c.getName()));
		}
		menu_Category.setText("Hii There");
	}
	// Event Listener on MenuItem[#menuItem_addCategory].onAction
	@FXML
	public void addCategory(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn_SearchByRecipe].onAction
	@FXML
	public void handleButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	private void initialize()
	
	    {
		

		    	List<Category> lc = ObjectUtilities.loadCategoryData();
				for(Category c: lc) {
					menu_Category.getItems().add(new MenuItem(c.getName()));
				}

	
	    }

}
