package cooking.view.design;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Accordion;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.TitledPane;

import java.util.ArrayList;
import java.util.List;

import cooking.model.concrete.Category;
import cooking.model.concrete.ObjectUtilities;
import cooking.model.concrete.Recipe;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.control.MenuItem;

import javafx.scene.control.Label;

import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.util.Callback;
import javafx.scene.control.Menu;

public class TemplateController {
	@FXML	private BorderPane bp_mainWindow;
	@FXML	private MenuItem mi_close;
	@FXML	private MenuItem mi_searchByRecipe;
	@FXML	private MenuItem mi_searchByFoodComponent;
	@FXML	private Menu menu_Category;
	@FXML	private MenuItem menuItem_addCategory;
	@FXML	private Label lbl_username;
	@FXML	private TextField txt_searchByRecipe;
	@FXML	private Button btn_SearchByRecipe;
	@FXML	private Button btn_SearchByComponent;
	@FXML	private TextField txt_searchByComponent;


	// Event Listener on MenuItem[#mi_close].onAction
	@FXML public void close(ActionEvent event) {
		Platform.exit();
	}
	
	// Event Listener on Menu[#menu_Category].onAction
	@FXML 	public void getCategory(ActionEvent event) {
		
		//menu_Category.setText("Hii There");
	}
	// Event Listener on MenuItem[#menuItem_addCategory].onAction
	@FXML
	public void addCategory(ActionEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#btn_SearchByRecipe].onAction
	@FXML
	public void handleButtonClick(ActionEvent event) throws Exception {
		@SuppressWarnings("unused")
		Stage st;
		Parent root = null;
		if (event.getSource() == btn_SearchByRecipe) {
			st = (Stage) btn_SearchByRecipe.getScene().getWindow();
			FXMLLoader loader= new FXMLLoader(getClass().getResource("RecipeList.fxml"));
			root = (Parent)loader.load();
			bp_mainWindow.setCenter(root);
		}
	}
}
